#!/bin/bash

if [ "$1" = 'up' ]; then
  docker-compose up -d
  exit 1
fi

if [ "$1" = 'down' ]; then
  docker-compose down -v
  exit 1
fi

if [ "$1" = 'build' ]; then
  docker-compose build
  exit 1
fi

if [ "$1" = 'rmvols' ]; then
  docker volume rm plesty_dbdata
  exit 1
fi

if [ "$1" = 'test' ]; then
  docker-compose exec app php artisan migrate:refresh --database=testing
  docker-compose exec app ./vendor/bin/phpunit ./tests/
  exit 1
fi

docker-compose exec "$@"